apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: sample-app-memory-leak
  namespace: default
spec:
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: sample-app
  stressors:
    memory:
      workers: 1
      size: "150MB"
